apiVersion: v1
kind: Service
metadata:
  name: multiarch-flask-service
spec:
  selector:
    app: multiarch-flask
  ports:
  - protocol: TCP
    port: 80 # External port
    targetPort: 8080 # Container port
