
name: build our image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_GITHUB_ACTIONS }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS }}
      #     aws-region: ${{ vars.AWS_REGION }}  

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      - name: build the image
        run: |
          REPOSITORY_URI=675021605538.dkr.ecr.ap-south-1.amazonaws.com/multiarch-flask

          docker buildx build --push \
            --tag $REPOSITORY_URI:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .